server.port: ${SERVER_PORT:8080}
#logging.level.org.apache.kafka: DEBUG
spring.kafka:
  bootstrap-servers: 192.168.1.6:32800,192.168.1.6:32801,192.168.1.6:32802
  listener.concurrency: 10
  consumer.group-id: consumer_group