server.port: ${SERVER_PORT:8080}
#logging.level.org.apache.kafka: DEBUG
spring.kafka:
  bootstrap-servers: 10.241.10.18:32774,10.241.10.18:32775,10.241.10.18:32776
  listener.concurrency: ${CONCURRENCY:100}
  consumer.group-id: consumer_group