server.port: ${SERVER_PORT:8080}
#logging.level.org.apache.kafka: DEBUG
spring.kafka:
  bootstrap-servers: 192.168.1.6:32793,192.168.1.6:32794,192.168.1.6:32795
  listener.concurrency: 3
  consumer.group-id: consumer_group